### ISSUE TITLE
1.0 milestone NMSM

### ISSUE THREAD

**Issue by Kimsw-G** [koreait0000/NMSM#3]
### 기획
- [x] 역할 분담
- [ ] 페이지 구성

### 개발
front - 박민지
- [ ] html 기본틀 (7/11까지)
- [ ] css

back - 김성욱 
- [ ] 회원가입 서비스 /regist()
- [ ] 소셜로그인 서비스 /login()
- [ ] 반려견 등록 서비스 /my/mypet()
- [ ] 예약관리 서비스 /my/mybook() 
- [ ] 찜목록 서비스 /my/myfav()
- [ ]  호텔 관리 서비스 /my/myhotel()

back - 임지영
- [ ] 호텔 검색 /hotel/list ()
- [ ] 호텔정보 /hotel/info ()
- [ ] 리뷰 /hotel/review ()
- [ ] 호텔예약 /hotel/book ()

**Comment by Kimsw-G** [comment]
이슈 분할했습니다
