### ISSUE TITLE
milestone KSW

### ISSUE THREAD

**Issue by Kimsw-G** [koreait0000/NMSM#6]
- [x] 회원가입 서비스 /regist()
- [ ] 소셜로그인 서비스 /login()
- [ ] 반려견 등록 서비스 /my/mypet()
- [ ] 예약관리 서비스 /my/mybook() 
- [x] 찜목록 서비스 /my/mylike()
- [x]  호텔 관리 서비스 /my/myhotel()

**Comment by Kimsw-G** [comment]
/my/mypet 페이지에서 할 수 있는 기능
@Lindsy-pak @ellenlim01
